# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[social]]
identifier = "email"
name = "email"
url = "mailto:pbenardis@proton.me"

[social.params]
icon = "brand-mail"

#[[social]]
#identifier = "github"
#name = "GitHub"
#url = "https://github.com/pbenardis"

#[social.params]
#icon = "brand-github"

[[social]]
identifier = "linkedin"
name = "LinkedIn"
url = "https://www.linkedin.com/in/pbenardis/"

[social.params]
icon = "brand-linkedin"

[[social]]
identifier = "website"
name = "website"
url = "https://www.benardis.gr"

[social.params]
icon = "brand-world-www"

[[social]]
identifier = "map"
name = "Google Maps"
url = "https://www.google.com/maps/place/%CE%A0%CE%91%CE%9D%CE%91%CE%93%CE%99%CE%A9%CE%A4%CE%97%CE%A3+%CE%9C%CE%A0%CE%95%CE%9D%CE%91%CE%A1%CE%94%CE%97%CE%A3-+%CE%99%CE%91%CE%A4%CE%A1%CE%99%CE%9A%CE%97+%CE%95%CE%9C%CE%92%CE%A1%CE%A5%CE%9F%CE%A5+%26+%CE%A5%CE%A0%CE%95%CE%A1%CE%97%CE%A7%CE%9F%CE%93%CE%A1%CE%91%CE%A6%CE%99%CE%91/@37.9876883,23.7565301,17z/data=!4m6!3m5!1s0x14a1bd5524c68889:0xc0a1bf9a0a170fed!8m2!3d37.9876841!4d23.759105!16s%2Fg%2F1tn1ypzc?entry=ttu&g_ep=EgoyMDI1MDMyNC4wIKXMDSoASAFQAw%3D%3D"

[social.params]
icon = "map-pin"

[[social]]
identifier = "copyright"
name = "όροι χρήσης-copyright"
url = "https://fetalneurology.gr/p/%CF%8C%CF%81%CE%BF%CE%B9-%CF%87%CF%81%CE%AE%CF%83%CE%B7%CF%82/"


[social.params]
icon = "copyright"

[[social]]
identifier = "phone"
name = "phone"
url = "https://fetalneurology.gr/p/%CF%81%CE%B1%CE%BD%CF%84%CE%B5%CE%B2%CE%BF%CF%8D/"


[social.params]
icon = "phone"

[[social]]
identifier = "english-language"
name = "English"
url = "https://fetalneurology.gr/p/english/"

[social.params]
icon = "alphabet-latin"





